// Roster data — 4 IT flatmates. Real names from user; skills/bios inferred from
// public GitHub data where available. LinkedIn data is not scrapable, so some
// bios are scaffolded — easy to refine once each flatmate provides specifics.

const ROSTER = [
  {
    id: "01",
    codename: "BORNO",
    name: "Davide Benedetti",
    title: "Junior Software Engineer",
    location: "Copenhagen",
    yearsExp: 1,
    bio: [
      "Junior engineer learning the craft — comfortable across backend and full-stack work, eager to ship and get feedback. Currently building fundamentals he'll lean on for the next decade.",
      "Curious by default — picks up new stacks fast, asks the question everyone else is afraid to ask in standup.",
    ],
    skills: [
      { name: "Java", level: 85 },
      { name: "Python", level: 82 },
      { name: "JavaScript / TS", level: 78 },
      { name: "SQL / Databases", level: 80 },
      { name: "Git / CI", level: 84 },
      { name: "Software Design", level: 78 },
    ],
    stats: { commits: "—", talks: 0, oss: "—" },
    quote: "Make it work, make it right, make it readable.",
    accent: "lime",
    linkedin: "https://www.linkedin.com/in/davide-benedetti-bb717a260/",
    github: "https://github.com/dadded01",
    cv: "#cv-davide",
  },
  {
    id: "02",
    codename: "PARO",
    name: "Luca Parolini",
    title: "Junior Security & Backend Engineer",
    location: "Copenhagen",
    yearsExp: 1,
    bio: [
      "Bachelor thesis: a post-authentication script that gates an OpenVPN server behind a Bitcoin payment — security and crypto, end to end. Builds at parox.dev on the side.",
      "Has shipped a secure distributed chat and a Java pipeline that scrapes online newspapers and surfaces the most important terms. Prefers his coffee like his code: black, no sugar, predictable.",
    ],
    skills: [
      { name: "Python", level: 90 },
      { name: "Java", level: 85 },
      { name: "Bitcoin / Crypto", level: 82 },
      { name: "Networking / VPN", level: 84 },
      { name: "Distributed Systems", level: 78 },
      { name: "Linux / OpenVPN", level: 85 },
    ],
    stats: { commits: "—", talks: 0, oss: 6 },
    quote: "Trust, but verify the signature.",
    accent: "cyan",
    linkedin: "https://www.linkedin.com/in/luca-parolini-40b98a202/",
    github: "https://github.com/cooparo",
    site: "https://parox.dev",
    cv: "#cv-luca",
  },
  {
    id: "03",
    codename: "STEGO",
    name: "Michael Fantinato",
    title: "Junior Software Engineer",
    location: "Copenhagen",
    yearsExp: 1,
    bio: [
      "Junior dev with a soft spot for clean code and end-to-end ownership. Still building muscle memory across the stack — and partial to systems that don't surprise you in production.",
      "Reliable code reviewer in training — the kind of teammate who actually reads the diff.",
    ],
    skills: [
      { name: "TypeScript", level: 84 },
      { name: "React", level: 82 },
      { name: "Node.js", level: 80 },
      { name: "Python", level: 78 },
      { name: "Docker", level: 76 },
      { name: "REST / GraphQL", level: 78 },
    ],
    stats: { commits: "—", talks: 0, oss: "—" },
    quote: "Boring code is a feature, not a bug.",
    accent: "magenta",
    linkedin: "https://www.linkedin.com/in/michael-fantinato-61971525a/",
    github: null,
    cv: "#cv-michael",
  },
  {
    id: "04",
    codename: "JIMPO",
    name: "Jinpeng Zhang",
    title: "Junior Engineer · Hackathon Builder",
    location: "Copenhagen",
    yearsExp: 1,
    bio: [
      "Junior engineer who recently shipped a techathon project end-to-end — turns a 48-hour idea into a working demo and keeps refactoring it on Monday.",
      "Bilingual, multi-stack, and pathologically curious. The flatmate most likely to pull an all-nighter to finish a side project nobody asked for.",
    ],
    skills: [
      { name: "JavaScript / TS", level: 84 },
      { name: "React", level: 82 },
      { name: "Python", level: 80 },
      { name: "Node.js", level: 78 },
      { name: "Rapid Prototyping", level: 90 },
      { name: "API Integration", level: 82 },
    ],
    stats: { commits: "—", talks: 0, oss: "—" },
    quote: "Ship the demo, then ship the docs.",
    accent: "amber",
    linkedin: "https://www.linkedin.com/in/jinpeng-zhang-946843204/",
    github: "https://github.com/Jimpoz/techathon",
    cv: "#cv-jinpeng",
  },
];

window.ROSTER = ROSTER;
