// Roster data — 4 IT flatmates. Real names from user; skills/bios inferred from
// public GitHub data where available. LinkedIn data is not scrapable, so some
// bios are scaffolded — easy to refine once each flatmate provides specifics.

const ROSTER = [
  {
    id: "01",
    codename: "BORNO",
    name: "Davide Benedetti",
    title: "IT Security Student",
    location: "Copenhagen",
    bio: [
      "Cybersecurity MSc student at Aalborg University, CompSci grad from Padova. Runs a real SOC lab with Wazuh and Sysmon, participates in bi-weekly CTF sessions, and does hands-on wireless security research — bridging AAU theory with real attack scenarios.",
      "ISC² Certified in Cybersecurity. Techathon winner. Seeks an entry-level role where curiosity is treated as a skill.",
    ],
    skills: [
      { name: "Python", level: 76 },
      { name: "Linux / Networking", level: 74 },
      { name: "Network Security", level: 72 },
      { name: "Java / C++", level: 73 },
      { name: "SQL", level: 68 },
      { name: "Cryptography / GRC", level: 65 },
    ],
    stats: { commits: "—", talks: 0, oss: "—" },
    quote: "Break it in the lab before it breaks in prod.",
    accent: "lime",
    linkedin: "https://www.linkedin.com/in/davide-benedetti-bb717a260/",
    github: "https://github.com/dadded01",
    email: "davidebenedetti1@gmail.com",
    cvPath: "assets/cv/Davide_Benedetti.pdf",
  },
  {
    id: "02",
    codename: "PARO",
    name: "Luca Parolini",
    title: "Computer Engineer & SysAdmin",
    location: "Copenhagen",
    bio: [
      "I'm a Computer Engineering grad and MSc Cybersecurity student with 4+ years running self-hosted infrastructure on Proxmox: DNS, VPN, storage, and services, all managed through declarative NixOS configuration.",
      "I build things that are reproducible and secure by design: from a Bitcoin-authenticated OpenVPN server for my thesis to a P2P encrypted chat with Double Ratchet. Currently researching runtime attack detection at the OS level.",
    ],
    skills: [
      { name: "Nix / NixOS", level: 90 },
      { name: "Distributed Systems", level: 80 },
      { name: "Networking / VPN", level: 84 },
      { name: "Linux Admin / Proxmox", level: 85 },
      { name: "Bitcoin", level: 82 },
      { name: "Python", level: 70 },
    ],
    stats: { commits: "—", talks: 0, oss: 6 },
    quote: "Improving daily work is even more important than doing daily work.",
    quoteSource: "Gene Kim, The Phoenix Project",
    accent: "cyan",
    linkedin: "https://www.linkedin.com/in/luca-parolini-40b98a202/",
    github: "https://github.com/cooparo",
    site: "https://parox.dev",
    email: "pparolini1@gmail.com",
    cvRepo: "cooparo/curriculum-vitae",
  },
  {
    id: "03",
    codename: "STEGO",
    name: "Michael Fantinato",
    title: "Full-Stack Dev & Automation Engineer",
    location: "Copenhagen",
    bio: [
      "Full-stack developer with 3+ years of production experience: built Flutter apps for industrial manufacturing clients at two companies, designed PLC automation systems, and led the driverless control stack on a Formula SAE autonomous vehicle.",
      "Bachelor's thesis: AI-powered production optimizer with microservices, FastAPI, React, and a custom Claude MCP server. Ships code from the factory floor to the autonomous racetrack.",
    ],
    skills: [
      { name: "Flutter / Dart", level: 88 },
      { name: "Python / FastAPI", level: 82 },
      { name: "React / Angular", level: 78 },
      { name: "LangChain / LLMs", level: 76 },
      { name: "Docker", level: 78 },
      { name: "Autonomous Systems", level: 74 },
    ],
    stats: { commits: "—", talks: 0, oss: "—" },
    quote: "From PLC to LLM — code is code.",
    accent: "magenta",
    linkedin: "https://www.linkedin.com/in/michael-fantinato-61971525a/",
    github: null,
    email: "fantinato.michael@gmail.com",
    cvPath: "assets/cv/Micheal_Fantinato.pdf",
  },
  {
    id: "04",
    codename: "JIMPO",
    name: "Jinpeng Zhang",
    title: "Full-Stack Engineer · MSc Student",
    location: "Copenhagen",
    yearsExp: 2,
    bio: [
      "Full-stack engineer with 2+ years of industry experience: Java/Spring Boot on a healthcare platform, fullstack banking apps with JHipster, and a RAG pipeline internship at a Copenhagen AI startup.",
      "Built ARIADNE — a multi-service indoor navigation platform with FastAPI, Neo4j/PostGIS, SwiftUI, and real-time YOLO-based AR way-finding. Now MSc Software Engineering at Aalborg University.",
    ],
    skills: [
      { name: "Java / Spring Boot", level: 88 },
      { name: "TypeScript / Angular", level: 85 },
      { name: "Python / FastAPI", level: 84 },
      { name: "AI / RAG", level: 82 },
      { name: "Databases", level: 82 },
      { name: "Docker / Kubernetes", level: 80 },
    ],
    stats: { commits: "—", talks: 0, oss: "—" },
    quote: "Ship it, then make it scale.",
    accent: "amber",
    linkedin: "https://www.linkedin.com/in/jinpeng-zhang-946843204/",
    github: "https://github.com/Jimpoz/techathon",
    email: "jimpo.jpz@gmail.com",
    cvPath: "assets/cv/Jinpeng_Zhang.pdf",
  },
];

window.ROSTER = ROSTER;
